apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: whdnybdrc-dotnet-basic-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/whdnybdrc-dotnet-basic-gitops